### ISSUE TITLE
FAV deleteById bug

### ISSUE THREAD

**Issue by Caspering** [Caspering/inventory_management#15]
http://localhost:8080/api/v1/fruitAndVeges/ delete by Id returns an error log instead of deleting the fav with the requested ID.

**Comment by ghost** [comment]
This works as expected. This may be a user error. Running the following request after a fresh start returned 200 OK:
```DELETE http://localhost:8080/api/v1/fruitAndVeges/1

HTTP/1.1 200 
Content-Length: 0
Date: Thu, 07 May 2020 03:42:04 GMT
Keep-Alive: timeout=60
Connection: keep-alive

<Response body is empty>

Response code: 200; Time: 158ms; Content length: 0 bytes
```
