### ISSUE TITLE
Add CSV dependency and implement CSV record to produce object mapper

### ISSUE THREAD

**Issue by ghost** [Caspering/inventory_management#7]
**Acceptance Criteria**

- Add Apache Commons CSV dependency: [Maven: Apache Commons CSV](https://mvnrepository.com/artifact/org.apache.commons/commons-csv/1.8)
- Implement converter class for extracting produce data from a CSVRecord object
- Unit test is added to test conversion: test the happy path and come up with a few edge cases

**Considerations**
- Here is the Apache Commons CSV documentation: [Apache Commons CSV Docs](https://commons.apache.org/proper/commons-csv/)
- Check out the CSVRecord Javadoc for information on how to extract fields
- We'll use this module in another issue when we implement processing an entire CSV input file

**Comment by Caspering** [comment]
This looks exciting>

**Comment by Caspering** [comment]
implemented univocity csv parser
